# Generated by Django 4.2.16 on 2026-05-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('test_type', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing')], max_length=20, verbose_name='Test turi')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='Qiyinlik')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiyligi (daqiqa)')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name="O'tish balli (%)")),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='mock_tests/audio/', verbose_name='Audio (Listening)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demo test',
                'verbose_name_plural': 'Demo testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice (A/B/C/D)'), ('true_false_not_given', 'True / False / Not Given'), ('fill_blank', "Bo'sh joyni to'ldirish")], default='mcq', max_length=30, verbose_name='Savol turi')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('instruction', models.CharField(blank=True, max_length=500, verbose_name="Ko'rsatma")),
                ('option_a', models.CharField(blank=True, max_length=500, verbose_name='Variant A')),
                ('option_b', models.CharField(blank=True, max_length=500, verbose_name='Variant B')),
                ('option_c', models.CharField(blank=True, max_length=500, verbose_name='Variant C')),
                ('option_d', models.CharField(blank=True, max_length=500, verbose_name='Variant D')),
                ('correct_answer', models.CharField(blank=True, max_length=200, verbose_name="To'g'ri javob")),
                ('correct_answers_json', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True, verbose_name='Tushuntirish')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('part_number', models.PositiveSmallIntegerField(default=1, verbose_name='Part raqami')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mock_tests.mocktest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MockPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Tartib')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='mock_tests.mocktest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Passage',
                'verbose_name_plural': "Passage'lar",
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('answers_json', models.JSONField(blank=True, default=dict)),
                ('score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mock_tests.mocktest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-started_at'],
            },
        ),
    ]
