# Generated by Django 4.2.16 on 2026-05-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockquestion',
            name='audio_timestamp',
            field=models.FloatField(blank=True, help_text='Listening: shu soniyadan audio ijro etiladi', null=True, verbose_name='Audio vaqti (soniya)'),
        ),
        migrations.AlterField(
            model_name='mockquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice (A/B/C/D)'), ('true_false_not_given', 'True / False / Not Given'), ('yes_no_not_given', 'Yes / No / Not Given'), ('fill_blank', "Bo'sh joyni to'ldirish"), ('sentence_completion', 'Sentence Completion'), ('essay', 'Essay (Writing)')], default='mcq', max_length=30, verbose_name='Savol turi'),
        ),
    ]
