# Generated by Django 4.2.16 on 2026-05-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_tests', '0002_phase2_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockattempt',
            name='ielts_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='IELTS band'),
        ),
        migrations.AddField(
            model_name='mockquestion',
            name='options_json',
            field=models.JSONField(blank=True, default=dict, help_text='Matching: {"options": [{"letter":"a","text":"..."}, ...]}'),
        ),
        migrations.AlterField(
            model_name='mockquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice (A/B/C/D)'), ('true_false_not_given', 'True / False / Not Given'), ('yes_no_not_given', 'Yes / No / Not Given'), ('fill_blank', "Bo'sh joyni to'ldirish"), ('sentence_completion', 'Sentence Completion'), ('essay', 'Essay (Writing)'), ('summary_completion', 'Summary Completion'), ('matching', 'Matching (A-H tanlash)')], default='mcq', max_length=30, verbose_name='Savol turi'),
        ),
    ]
