# Generated by Django 4.2.16 on 2026-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_tests', '0003_phase3_band_and_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice (A/B/C/D)'), ('true_false_not_given', 'True / False / Not Given'), ('yes_no_not_given', 'Yes / No / Not Given'), ('fill_blank', "Bo'sh joyni to'ldirish"), ('sentence_completion', 'Sentence Completion'), ('essay', 'Essay (Writing)'), ('summary_completion', 'Summary Completion'), ('matching', 'Matching (A-H tanlash)'), ('summary_box', 'Summary + box (inline qavslar)'), ('speaking', 'Speaking (audio yozish)')], default='mcq', max_length=30, verbose_name='Savol turi'),
        ),
    ]
