# Generated by Django 5.1.7 on 2025-12-18 17:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our School', max_length=200)),
                ('text', models.TextField()),
                ('mission', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/about/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text="e.g., '3 months', '6 weeks'", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('promo_video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('promo_video_file', models.FileField(blank=True, help_text='Local video file', null=True, upload_to='videos/courses/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font Awesome icon class or emoji', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('bio', models.TextField()),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL for greeting video', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/teachers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='blog.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IELTSCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='certificates/students/')),
                ('ielts_score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('certificate_image', models.ImageField(upload_to='certificates/')),
                ('date_obtained', models.DateField()),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='blog.course')),
            ],
            options={
                'ordering': ['-date_obtained', '-ielts_score'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL for video testimonial', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/testimonials/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='blog.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_type', models.CharField(choices=[('course_lesson', 'Course Lesson'), ('promo', 'Promo Video'), ('testimonial', 'Testimonial'), ('about', 'About School'), ('other', 'Other')], max_length=20)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='video_previews/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_videos', to='blog.course')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
