# Generated by Django 5.1.7 on 2025-12-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='promo_video_url',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='about',
            name='video_file',
            field=models.FileField(blank=True, help_text='Local video file only', null=True, upload_to='videos/about/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='promo_video_file',
            field=models.FileField(blank=True, help_text='Local video file only', null=True, upload_to='videos/courses/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='video_file',
            field=models.FileField(blank=True, help_text='Local video file only', null=True, upload_to='videos/teachers/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_file',
            field=models.FileField(blank=True, help_text='Local video file only', null=True, upload_to='videos/testimonials/'),
        ),
    ]
