# Generated by Django 5.1.7 on 2025-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Step number (1, 2, 3, 4, etc.)')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fas fa-user-plus', 'Sign Up'), ('fas fa-clipboard-check', 'Assessment'), ('fas fa-chalkboard-teacher', 'Learn'), ('fas fa-trophy', 'Excel'), ('fas fa-book', 'Book'), ('fas fa-certificate', 'Certificate'), ('fas fa-users', 'Users'), ('fas fa-graduation-cap', 'Graduation')], help_text='Font Awesome icon class', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order in which step appears (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['order', 'step_number'],
            },
        ),
    ]
