# Generated by Django 5.2.9 on 2026-02-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_processstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Rasm')),
                ('bio', models.TextField(verbose_name="O'quvchi haqida ma'lumot")),
                ('video_file', models.FileField(blank=True, help_text="O'quvchi videosi (faqat lokal fayl)", null=True, upload_to='videos/students/', verbose_name='Video')),
                ('video_url', models.URLField(blank=True, help_text='YouTube yoki Vimeo video havolasi', null=True, verbose_name='Video URL')),
                ('achievement', models.CharField(blank=True, help_text='Muvaffaqiyat (masalan: IELTS 7.5, TOEFL 100)', max_length=200, verbose_name='Muvaffaqiyat')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Asosiy sahifada ko'rsatish")),
                ('order', models.IntegerField(default=0, help_text="Tartib raqami (kichik raqamlar birinchi ko'rsatiladi)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_results', to='blog.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': "O'quvchi natijasi",
                'verbose_name_plural': "O'quvchilarning natijalari",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
