# Generated by Django 5.2.9 on 2026-02-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SATCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text="e.g., '3 months', '6 weeks'", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper-intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sat_courses/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text="Ko'rsatish tartibi (kichik raqam birinchi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAT Course',
                'verbose_name_plural': 'SAT Courses',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]

